app:
  name: youtube-download-api
  services:
    - name: api
      type: web
      build:
        type: buildpack
      instance_type: nano
      ports:
        - port: 8000
          protocol: http
      env:
        - key: PORT
          value: "8000"
      routes:
        - path: /
          port: 8000
